version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: currency
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  initdb:
    image: postgres
    depends_on:
      - db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]
